3-9実装例（二項ロジスティック回帰モデル）

二項ロジスティック回帰モデルをbrmsで実装
```{r}
# パッケージ読込
library(rstan)
library(brms)

# 計算高速化
rstan_options(auto_write=TRUE)  # コンパイルファイルの保存
options(mc.cores = parallel::detectCores())  # 計算並列化

# データの読込と可視化
germination_dat <- read.csv("./sample_data/3-9-1-germination.csv")
ggplot(data=germination_dat, mapping=aes(x=nutrition, y=germination)) +
  geom_point(aes(color=solar)) +
  labs(title="Relation between nutrition and germination")

# 二項ロジスティック回帰モデル作成
glm_binom_brms <- brm(
  formula = germination | trials(size) ~ solar + nutrition,
  family = binomial(),  # リンク関数は自動でロジット関数に指定される
  data = germination_dat,
  seed = 1,
  prior = c(set_prior("", class = "Intercept"))
)

# 結果の表示
glm_binom_brms
```
各天気・栄養量での期待値のベイズ信用区間表示
```{r}
eff <- conditional_effects(glm_binom_brms, 
                           effects = "nutrition:solar",
                           conditions = data.frame(size = 10))
plot(eff, points=TRUE)
```
各天気・栄養量でのベイズ予測区間表示
```{r}
eff <- conditional_effects(glm_binom_brms, 
                           effects = "nutrition:solar",
                           conditions = data.frame(size = 10),
                           method = "predict")
plot(eff, points=TRUE)
```


二項ロジスティック回帰モデルをStanで実装（デザイン行列不使用）
```{r}
# パッケージ読込
library(rstan)

# 計算高速化
rstan_options(auto_write=TRUE)  # コンパイルファイルの保存
options(mc.cores = parallel::detectCores())  # 計算並列化

# データの読込と可視化
germination_dat <- read.csv("./sample_data/3-9-1-germination.csv")
sample_size <- nrow(germination_dat) # サンプルサイズ
ggplot(data=germination_dat, mapping=aes(x=nutrition, y=germination)) +
  geom_point(aes(color=solar)) +
  labs(title="Relation between nutrition and germination")

# カテゴリ変数のダミー変数化
solar_dummy <- as.numeric(germination_dat$solar == "sunshine")

# 事後予測分布算出用説明変数データ
NUTRITION_PRED <- 1:10  # 栄養1-10
SIZE_PRED <- c(4, 10, 25)  # 試行数

# list形式にデータをまとめる（stanファイルのdataブロックと名称を揃える）
data_list <- list(
  N = sample_size,
  germination  = germination_dat$germination,
  binom_size = germination_dat$size,
  nutrition = germination_dat$nutrition,
  solar = solar_dummy,
  N_pred_nutr = length(NUTRITION_PRED),
  N_pred_size = length(SIZE_PRED),
  nutr_pred = NUTRITION_PRED,
  size_pred = SIZE_PRED
  )

# MCMC実行
mcmc_result <- stan(
  file = "./stan/3-9-2-glm-binom-2.stan", # stanファイルのパス
  data = data_list, # 対象データ
  seed = 1         # 乱数シード
)

# 結果の表示
print(
  mcmc_result,           # MCMCサンプルの結果
  probs = c(0.025, 0.5, 0.975)  # 中央値と95%信用区間を出力
)
```
トレースプロットと事後分布の可視化
```{r}
library(bayesplot)
# MCMCサンプル抽出
mcmc_sample_raw <- rstan::extract(mcmc_result, permuted = FALSE)
# トレースプロットと事後分布
mcmc_combo(
  mcmc_sample_raw,
  pars = c("Intercept", "b_nutrition", "b_solar")
)
```
pの信用区間を散布図上に表示
```{r}
# pの50%信用区間と95%信用区間を取得(晴れ)
mcmc_sample <- rstan::extract(mcmc_result, permuted = TRUE)
qua_p_sunshine <- apply(mcmc_sample$p_pred_sunshine,
                        2,
                        quantile,
                        probs=c(0.025, 0.25, 0.50, 0.75, 0.975))
df_qua_p_sunshine <- data.frame(
  nutrition=NUTRITION_PRED,
  t(qua_p_sunshine),
  check.names = FALSE
)
# pの50%信用区間と95%信用区間を取得(曇り)
qua_p_shade <- apply(mcmc_sample$p_pred_shade,
                     2,
                     quantile,
                     probs=c(0.025, 0.25, 0.50, 0.75, 0.975))
df_qua_p_shade <- data.frame(
  nutrition=NUTRITION_PRED,
  t(qua_p_shade),
  check.names = FALSE
)
# 色リスト
library(scales)
COLOR_LIST = hue_pal()(2)

# 二項分布の試行回数毎に信用区間をプロット
plots <- list()
for(j in 1:length(SIZE_PRED)){
  binom_size <- SIZE_PRED[j]  # 試行回数
  # 試行回数が範囲内に入るデータを抜き出す
  if(j == 1) size_min <- 1  # 試行回数の下限(標準偏差が√nに比例するのでルートとって平均)
  else size_min <- ((sqrt(SIZE_PRED[j]) + sqrt(SIZE_PRED[j - 1]))/2)^2
  if(j == length(SIZE_PRED)) size_max <- 2147483647  # 試行回数の上限
  else size_max <- ((sqrt(SIZE_PRED[j]) + sqrt(SIZE_PRED[j + 1]))/2)^2
  data_trial_filter <- germination_dat[germination_dat$size >= size_min & germination_dat$size < size_max, ]
  data_trial_filter <- data.frame(
    data_trial_filter, 
    probability = data_trial_filter$germination/data_trial_filter$size
    )
  # 「p*試行回数」の50%信用区間と95%信用区間をプロット
  plots[[j]] <- ggplot() +
    theme_bw(base_size=18) +
    geom_ribbon(data=df_qua_p_shade, aes(x=nutrition, ymin=`2.5%`, ymax=`97.5%`),
                fill=COLOR_LIST[1], alpha=1/4) +
    geom_ribbon(data=df_qua_p_shade, aes(x=nutrition, ymin=`25%`, ymax=`75%`),
                fill=COLOR_LIST[1], alpha=1/2) +
    geom_line(data=df_qua_p_shade, aes(x=nutrition, y=`50%`),
              colour=COLOR_LIST[1], size=1) +
    geom_ribbon(data=df_qua_p_sunshine, aes(x=nutrition, ymin=`2.5%`, ymax=`97.5%`),
                fill=COLOR_LIST[2], alpha=1/4) +
    geom_ribbon(data=df_qua_p_sunshine, aes(x=nutrition, ymin=`25%`, ymax=`75%`),
                fill=COLOR_LIST[2], alpha=1/2) +
    geom_line(data=df_qua_p_sunshine, aes(x=nutrition, y=`50%`),
              colour=COLOR_LIST[2], size=1) +
    geom_point(data=data_trial_filter, aes(x=nutrition, y=probability, color=solar),
                shape=1, size=2) +
    scale_color_manual(values=COLOR_LIST) +
    labs(y='probability', title=paste('Credible interval N=', binom_size, ' (', round(size_min), ' to ', ceiling(size_max)-1, ')', sep=""))
}
plots
```
予測区間を散布図上に表示
```{r}
# MCMCサンプルを取得
mcmc_sample <- rstan::extract(mcmc_result, permuted = TRUE)
# 色リスト
library(scales)
COLOR_LIST = hue_pal()(2)

plots <- list()
# 二項分布の試行回数毎に予測区間をプロット
for(j in 1:length(SIZE_PRED)){
  binom_size <- SIZE_PRED[j]  # 試行回数
  # 50%予測区間と95%予測区間を取得(晴れ)
  qua_germ_sunshine <- apply(mcmc_sample$germ_pred_sunshine[,j,],
                             2,
                             quantile,
                             probs=c(0.025, 0.25, 0.50, 0.75, 0.975))
  qua_germ_sunshine <- qua_germ_sunshine / binom_size  # 回数から確率に変換
  df_qua_germ_sunshine <- data.frame(
    nutrition=NUTRITION_PRED,
    t(qua_germ_sunshine),
    check.names = FALSE
  )
  # 50%予測区間と95%予測区間を取得(曇り)
  qua_germ_shade <- apply(mcmc_sample$germ_pred_shade[,j,],
                          2,
                          quantile,
                          probs=c(0.025, 0.25, 0.50, 0.75, 0.975))
  qua_germ_shade <- qua_germ_shade / binom_size  # 回数から確率に変換
  df_qua_germ_shade <- data.frame(
    nutrition=NUTRITION_PRED,
    t(qua_germ_shade),
    check.names = FALSE
  )

  # 試行回数が範囲内に入るデータを抜き出す
  if(j == 1) size_min <- 1  # 試行回数の下限(標準偏差が√nに比例するのでルートとって平均)
  else size_min <- ((sqrt(SIZE_PRED[j]) + sqrt(SIZE_PRED[j - 1]))/2)^2
  if(j == length(SIZE_PRED)) size_max <- 2147483647  # 試行回数の上限
  else size_max <- ((sqrt(SIZE_PRED[j]) + sqrt(SIZE_PRED[j + 1]))/2)^2
  data_trial_filter <- germination_dat[germination_dat$size >= size_min & germination_dat$size < size_max, ]
  data_trial_filter <- data.frame(
    data_trial_filter, 
    probability = data_trial_filter$germination/data_trial_filter$size
    )
  # 「p*試行回数」の50%信用区間と95%信用区間をプロット
  plots[[j]] <- ggplot() +
    theme_bw(base_size=18) +
    geom_ribbon(data=df_qua_germ_shade, aes(x=nutrition, ymin=`2.5%`, ymax=`97.5%`),
                fill=COLOR_LIST[1], alpha=1/4) +
    geom_ribbon(data=df_qua_germ_shade, aes(x=nutrition, ymin=`25%`, ymax=`75%`),
                fill=COLOR_LIST[1], alpha=1/2) +
    geom_line(data=df_qua_germ_shade, aes(x=nutrition, y=`50%`),
              colour=COLOR_LIST[1], size=1) +
    geom_ribbon(data=df_qua_germ_sunshine, aes(x=nutrition, ymin=`2.5%`, ymax=`97.5%`),
                fill=COLOR_LIST[2], alpha=1/4) +
    geom_ribbon(data=df_qua_germ_sunshine, aes(x=nutrition, ymin=`25%`, ymax=`75%`),
                fill=COLOR_LIST[2], alpha=1/2) +
    geom_line(data=df_qua_germ_sunshine, aes(x=nutrition, y=`50%`),
              colour=COLOR_LIST[2], size=1) +
    geom_point(data=data_trial_filter, aes(x=nutrition, y=probability, color=solar),
                shape=1, size=2) +
    scale_color_manual(values=COLOR_LIST) +
    labs(y='probability', title=paste('Prediction interval N=', binom_size, ' (', round(size_min), ' to ', ceiling(size_max)-1, ')', sep=""))
}
plots
```


二項ロジスティック回帰モデルをStanで実装（デザイン行列使用）
```{r}
# パッケージ読込
library(rstan)

# 計算高速化
rstan_options(auto_write=TRUE)  # コンパイルファイルの保存
options(mc.cores = parallel::detectCores())  # 計算並列化

# データの読込と可視化
germination_dat <- read.csv("./sample_data/3-9-1-germination.csv")
ggplot(data=germination_dat, mapping=aes(x=nutrition, y=germination)) +
  geom_point(aes(color=solar)) +
  labs(title="Relation between nutrition and germination")

# デザイン行列の作成
formula_binomial <- formula(germination | size ~ solar + nutrition)
design_mat <- model.matrix(formula_binomial, germination_dat)

# list形式にデータをまとめる（stanファイルのdataブロックと名称を揃える）
data_list <- list(
  N = nrow(germination_dat),  # データ数
  K = ncol(design_mat),  # デザイン行列の列数(weatherのユニーク数)
  Y = germination_dat$germination,  # 応答変数
  binom_size = germination_dat$size,  # 試行数
  X = design_mat  # デザイン行列
)

# MCMC実行
mcmc_result <- stan(
  file = "./stan/3-9-3-glm-binom-design-matrix.stan", # stanファイルのパス
  data = data_list, # 対象データ
  seed = 1         # 乱数シード
)

# 結果の表示
print(
  mcmc_result,           # MCMCサンプルの結果
  probs = c(0.025, 0.5, 0.975)  # 中央値と95%信用区間を出力
)
```
Stanで実装した二項ロジスティック回帰モデルの信用区間と予測区間を表示
```{r}
# MCMCサンプルを取り出す（事後予測分布のMCMCサンプルは含まない）
mcmc_sample <- rstan::extract(mcmc_result, permuted = TRUE)
mcmc_b <- mcmc_sample$b  # 線形予測子係数のMCMCサンプル

N_mcmc <- length(mcmc_sample$lp__)  # MCMCサンプルの個数
cat_unique <- sort(unique(germination_dat$solar))  # カテゴリ変数のユニーク値
mat_colnames <- colnames(design_mat)  # デザイン行列の列名
X_min <- min(germination_dat$nutrition)
X_max <- max(germination_dat$nutrition)

# 事後予測分布算出用説明変数データ
SIZE_PRED <- c(4, 10, 25)  # 試行数
X_pred <- floor(X_min):ceiling(X_max)  # 描画対象の説明変数範囲（本例では栄養量）
N_X <- length(X_pred)  # 説明変数範囲の要素数

# 色リスト
library(scales)
COLOR_LIST = hue_pal()(length(cat_unique))

plots_p <- list()     # pの信用区間描画用ggplotオブジェクトのリスト
plots_pred <- list()  # 予測区間描画用ggplotオブジェクトのリスト
# 二項分布の試行回数毎に予測区間をプロット
for(j in 1:length(SIZE_PRED)){
  binom_size <- SIZE_PRED[j]  # 試行回数
  # pの信用区間描画用ggplotオブジェクト
  p_p <- ggplot() +
    theme_bw(base_size=18)
  # 予測区間描画用ggplotオブジェクト
  p_pred <- ggplot() +
    theme_bw(base_size=18)
  # 試行回数が範囲内に入るデータを抜き出す
  if(j == 1) size_min <- 1  # 試行回数の下限(標準偏差が√nに比例するのでルートとって平均)
  else size_min <- ((sqrt(SIZE_PRED[j]) + sqrt(SIZE_PRED[j - 1]))/2)^2
  if(j == length(SIZE_PRED)) size_max <- 2147483647  # 試行回数の上限
  else size_max <- ((sqrt(SIZE_PRED[j]) + sqrt(SIZE_PRED[j + 1]))/2)^2
  data_trial_filter <- germination_dat[germination_dat$size >= size_min & germination_dat$size < size_max, ]
  data_trial_filter <- data.frame(
    data_trial_filter, 
    probability = data_trial_filter$germination/data_trial_filter$size
    )
  
  # カテゴリ変数ごとにループ
  for(i_cat in 1:length(cat_unique)){
    cat_name = cat_unique[i_cat]  # カテゴリ名
    # 説明変数行列のdataframeを作成(デザイン行列に列を合わせる)
    for(i_matcol in 1:length(mat_colnames)){
      # 列を作成
      colname <- mat_colnames[i_matcol]  # デザイン行列の列名
      if(colname == "(Intercept)"){
        # 切片列
        df_tmp <- data.frame(rep(1, times = 1))
      } else if(colname == paste("solar",cat_name, sep="")){
        # 該当するカテゴリ変数列
        df_tmp <- data.frame(rep(1, times = N_X))
      } else if(colname == "nutrition"){
        # 数値変数列
        df_tmp <- data.frame(X_pred)
      } else{
        # 該当しないカテゴリ変数列
        df_tmp <- data.frame(rep(0, times = N_X))
      }
      colnames(df_tmp) <- colname
      
      if(i_matcol == 1){
        # 最初の列の時、dataframeを新たに作成
        df_exp <- df_tmp
      }else{
        # 列を追加
        df_exp <- data.frame(df_exp, df_tmp)
      }
    }
    #print(df_exp)
    # lambdaと事後予測分布のMCMCサンプルを作成
    mcmc_p <- as.data.frame(matrix(nrow=N_mcmc, ncol=N_X))  # pのMCMCサンプル格納用
    mcmc_y <- as.data.frame(matrix(nrow=N_mcmc, ncol=N_X))  # 予測分布MCMCサンプル格納用
    for (i in 1:N_X){
      # pのMCMCサンプル = exp(線形予測子係数MCMCサンプル * 説明変数行列)
      mcmc_p[,i] <- inv_logit_scaled(mcmc_b %*% t(as.matrix(df_exp[i,])))
      # 事後予測分布のMCMCサンプルを正規分布乱数から生成(binom_sizeで割って確率化)
      mcmc_y[,i] <- rbinom(n=N_mcmc, size=binom_size, prob=mcmc_p[,i]) / binom_size
    }
    
    # pの50%信用区間と95%信用区間を取得
    qua_p <- apply(mcmc_p,
                    2,
                    quantile,
                    probs=c(0.025, 0.25, 0.50, 0.75, 0.975))
    df_qua_p <- data.frame(
      nutrition=X_pred,
      t(qua_p),
      check.names = FALSE
      )
    # pの信用区間描画用ggplotオブジェクト追加
    p_p <- p_p +
    geom_ribbon(data=df_qua_p, aes(x=nutrition, ymin=`2.5%`, ymax=`97.5%`),
                fill=COLOR_LIST[i_cat], alpha=1/4) +
    geom_ribbon(data=df_qua_p, aes(x=nutrition, ymin=`25%`, ymax=`75%`),
                fill=COLOR_LIST[i_cat], alpha=1/2) +
    geom_line(data=df_qua_p, aes(x=nutrition, y=`50%`),
              colour=COLOR_LIST[i_cat], size=1)
    
    # 50%予測区間と95%予測区間を取得
    qua_pred <- apply(mcmc_y,
                      2,
                      quantile,
                      probs=c(0.025, 0.25, 0.50, 0.75, 0.975)
                      )
    df_qua_pred <- data.frame(
      nutrition=X_pred,
      t(qua_pred),
      check.names = FALSE
      )
    # 予測区間描画用ggplotオブジェクト追加
    p_pred <- p_pred +
    geom_ribbon(data=df_qua_pred, aes(x=nutrition, ymin=`2.5%`, ymax=`97.5%`),
                fill=COLOR_LIST[i_cat], alpha=1/6) +
    geom_ribbon(data=df_qua_pred, aes(x=nutrition, ymin=`25%`, ymax=`75%`),
                fill=COLOR_LIST[i_cat], alpha=1/3) +
    geom_line(data=df_qua_pred, aes(x=nutrition, y=`50%`),
              colour=COLOR_LIST[i_cat], size=1)
  }
  
  # pの50%信用区間と95%信用区間をプロット
  p_p <- p_p +
    geom_point(data=data_trial_filter, aes(x=nutrition, y=probability, color=solar),
                shape=1, size=2) +
    scale_color_manual(values=COLOR_LIST) + 
    labs(y='probability', title=paste('Credible interval N=', binom_size, ' (', round(size_min), ' to ', ceiling(size_max)-1, ')', sep=""))
    plots_p[[j]] <- p_p
    
  # 50%予測区間と95%予測区間をプロット
  p_pred <- p_pred +
    geom_point(data=data_trial_filter, aes(x=nutrition, y=probability, color=solar),
                shape=1, size=2) +
    scale_color_manual(values=COLOR_LIST) + 
    labs(y='probability', title=paste('Prediction interval N=', binom_size, ' (', round(size_min), ' to ', ceiling(size_max)-1, ')', sep=""))
    plots_pred[[j]] <- p_pred
}
plots_p
plots_pred
```

