ユースケース4: 重回帰

手順1. 確率モデルの構築
散布図描画
```{r}
# データ読込（irisデータセットのsepal_widthとspecies）
df_iris <- data.frame(
  petal_width = iris$Petal.Width,
  petal_length = iris$Petal.Length,
  sepal_length = iris$Sepal.Length
)
# ggpairs散布図描画
library(GGally)
p<-ggpairs(df_iris)
p
```
手順2. MCMCでパラメータの事後確率分布算出

2-1: MCMC実行
```{r}
# パッケージ読込
library(rstan)

# 計算高速化
rstan_options(auto_write=TRUE)  # コンパイルファイルの保存
options(mc.cores = parallel::detectCores())  # 計算並列化

# 事後予測分布の横軸となる説明変数のベクトル
SEPAL_LENGTH_BY = 1.0
SEPAL_LENGTH_PRED <- seq(4, 8, by=SEPAL_LENGTH_BY)
PETAL_LENGTH_BY = 0.5
PETAL_LENGTH_PRED <- seq(1, 7, by=PETAL_LENGTH_BY)


# list形式にデータをまとめる（stanファイルのdataブロックと名称を揃える）
N <- nrow(iris)  # データ数
data_list <- list(
  N = N,
  petal_width = df_iris$petal_width,
  petal_length = df_iris$petal_length,
  sepal_length = df_iris$sepal_length,
  N_pred_1 = length(PETAL_LENGTH_PRED),
  N_pred_2 = length(SEPAL_LENGTH_PRED),
  petal_length_pred = PETAL_LENGTH_PRED,
  sepal_length_pred = SEPAL_LENGTH_PRED
  )
data_list

# MCMC実行
mcmc_result <- stan(
  file = "./stan/usecase4_multiple_regression.stan", # stanファイルのパス
  data = data_list, # 対象データ
  seed = 1,         # 乱数シード
  chains = 4,       # 初期値の個数（全初期値で近い結果となれば収束と判断）
  iter = 2000,      # サンプリングの繰り返し数
  warmup = 1000,    # バーンイン期間（収束前と見なして捨てるサンプル数）
  thin = 1          # 間引き数（1なら間引きなし）
)
```
2-2: MCMC結果の概要確認
```{r}
options(max.print=2000) # printの表示上限を増やす(lp__が表示されるように)
print(
  mcmc_result,                  # MCMCサンプルの結果
  probs = c(0.005, 0.025, 0.5, 0.975, 0.995)  # 中央値と95%, 99%信用区間を出力
)
```
手順3: モデルの評価

3-1: トレースプロットによる収束確認
```{r}
# トレースプロット（バーンイン期間を含まない）
traceplot(mcmc_result, pars = c("Intercept", "b_petal_length", "b_sepal_length", "sigma", "lp__")) +
  labs(title="Without warmup")
# トレースプロット（バーンイン期間を含む）
traceplot(mcmc_result, inc_warmup=T, pars = c("Intercept", "b_petal_length", "b_sepal_length", "sigma", "lp__")) +
  labs(title="Including warmup")
```
3-2: MCMCサンプルの抽出
```{r}
# MCMCサンプルの抽出(`permuted=FALSE`でMCMCサンプルの並び順保持)
mcmc_sample_raw <- rstan::extract(mcmc_result, permuted = FALSE)
dim(mcmc_sample_raw)  # MCMCサンプルの要素数（iter-warmup × chains x パラメータ数）
dimnames(mcmc_sample_raw)  # 各々の名称（iterations, chains, parameters）
```
3-3-1: bayesplotによる事後分布（信用区間）の可視化
```{r}
library(bayesplot)
# ヒストグラム描画
mcmc_hist(mcmc_sample_raw, pars = c("Intercept", "b_petal_length", "b_sepal_length", "sigma"))
# カーネル密度推定
mcmc_dens(mcmc_sample_raw, pars = c("Intercept", "b_petal_length", "b_sepal_length", "sigma"))
# 信用区間
mcmc_intervals(
  mcmc_sample_raw, pars = c("Intercept", "b_petal_length", "b_sepal_length", "sigma"),
  prob = 0.95,  # 太い線の範囲（95%信用区間）
  prob_outer = 0.99  # 細い線の範囲（99%信用区間）
)
```
3-3-2: muの信用区間を散布図上に表示
```{r}
# MCMCサンプル取得(`permuted=TRUE`を指定)
mcmc_sample <- rstan::extract(mcmc_result, permuted = TRUE)

# 色リスト
library(scales)
COLOR_LIST = hue_pal()(2)
# 描画用ggplotオブジェクトのリスト
plots_mu <- list()

# 説明変数2(sepal_length)ごとに信用区間をプロット
for(i_2 in 1:length(SEPAL_LENGTH_PRED)){
  sepal_length <- SEPAL_LENGTH_PRED[i_2] # 使用するsepal_length
  # muの信用区間描画用ggplotオブジェクト
  p_mu <- ggplot() +
    theme_bw(base_size=18)
  
  # 試行回数が範囲内に入るデータを抜き出す
  if(i_2 == 1) sepal_length_min <- -2147483647 # 範囲の下限
  else sepal_length_min <- sepal_length - SEPAL_LENGTH_BY/2
  if(i_2 == length(SEPAL_LENGTH_PRED)) sepal_length_max <- 2147483647 # 範囲の上限
  else sepal_length_max <- sepal_length + SEPAL_LENGTH_BY/2
  data_sepal_filtered <- df_iris[df_iris$sepal_length>=sepal_length_min & df_iris$sepal_length<sepal_length_max, ]
  
  # muの95%信用区間と99%信用区間を取得
  qua_mu <- apply(mcmc_sample$mu_pred[,,i_2],
                  2,
                  quantile,
                  probs=c(0.005, 0.025, 0.50, 0.975, 0.995))
  df_qua_mu <- data.frame(
    petal_length=PETAL_LENGTH_PRED,
    t(qua_mu),
    check.names = FALSE
    )
  
  # muの95%信用区間と99%信用区間をプロット
  p_mu <- p_mu +
    geom_ribbon(data=df_qua_mu, 
                aes(x=petal_length, ymin=`0.5%`, ymax=`99.5%`),
                fill='black', alpha=1/6) +
    geom_ribbon(data=df_qua_mu, 
                aes(x=petal_length, ymin=`2.5%`, ymax=`97.5%`),
                fill='black', alpha=2/6) +
    geom_line(data=df_qua_mu, aes(x=petal_length, y=`50%`), size=1) +
    geom_point(data=data_sepal_filtered, 
               aes(x=petal_length, y=petal_width)) +
    labs(y='petal_width', title='Credible interval of `mu`',
         subtitle=paste('sepal_length=', sepal_length, ' (', sepal_length_min, ' to ', sepal_length_max, ')', sep=""))
  plots_mu[[i_2]] <- p_mu
}
# 全ての図をプロット
plots_mu
```
3-4: 予測区間を散布図上に表示
```{r}
# 色リスト
library(scales)
COLOR_LIST = hue_pal()(2)
# 描画用ggplotオブジェクトのリスト
plots_pred <- list()

# 説明変数2(sepal_length)ごとに予測区間をプロット
for(i_2 in 1:length(SEPAL_LENGTH_PRED)){
  sepal_length <- SEPAL_LENGTH_PRED[i_2] # 使用するsepal_length
  # 予測区間描画用ggplotオブジェクト
  p_pred <- ggplot() +
    theme_bw(base_size=18)
  
  # 試行回数が範囲内に入るデータを抜き出す
  if(i_2 == 1) sepal_length_min <- -2147483647 # 範囲の下限
  else sepal_length_min <- sepal_length - SEPAL_LENGTH_BY/2
  if(i_2 == length(SEPAL_LENGTH_PRED)) sepal_length_max <- 2147483647 # 範囲の上限
  else sepal_length_max <- sepal_length + SEPAL_LENGTH_BY/2
  data_sepal_filtered <- df_iris[df_iris$sepal_length>=sepal_length_min & df_iris$sepal_length<sepal_length_max, ]
  
  # 95%予測区間と99%予測区間を取得
  qua_pred <- apply(mcmc_sample$petal_width_pred[,,i_2],
                  2,
                  quantile,
                  probs=c(0.005, 0.025, 0.50, 0.975, 0.995))
  df_qua_pred <- data.frame(
    petal_length=PETAL_LENGTH_PRED,
    t(qua_pred),
    check.names = FALSE
    )
  
  # 95%予測区間と99%予測区間をプロット
  p_pred <- p_pred +
    geom_ribbon(data=df_qua_pred, 
                aes(x=petal_length, ymin=`0.5%`, ymax=`99.5%`),
                fill='black', alpha=1/6) +
    geom_ribbon(data=df_qua_pred, 
                aes(x=petal_length, ymin=`2.5%`, ymax=`97.5%`),
                fill='black', alpha=2/6) +
    geom_line(data=df_qua_pred, aes(x=petal_length, y=`50%`), size=1) +
    geom_point(data=data_sepal_filtered, 
               aes(x=petal_length, y=petal_width)) +
    labs(y='petal_width', title='Prediction interval',
         subtitle=paste('sepal_length=', sepal_length, ' (', sepal_length_min, ' to ', sepal_length_max, ')', sep=""))
  plots_pred[[i_2]] <- p_pred
}
# 全ての図をプロット
plots_pred
```
3-5: 異常検知
```{r}
# 異常検知の閾値（指定した予測区間の外側なら異常とみなす）
P_THRESHOLD = 0.99
lower = (1 - P_THRESHOLD)/2  # 下限%
upper = 1 - lower  # 上限%

# パラメータごとのMCMCサンプルを保持
mcmc_Intercept <- mcmc_sample$Intercept
mcmc_b_petal_length <- mcmc_sample$b_petal_length
mcmc_b_sepal_length <- mcmc_sample$b_sepal_length
mcmc_sigma <- mcmc_sample$sigma

# 平均muと事後予測分布のMCMCサンプルを、データの説明変数ごとに作成
N_mcmc <- length(mcmc_sample$lp__)  # MCMCサンプルの個数
mcmc_mu <- as.data.frame(matrix(nrow=N_mcmc, ncol=N))  # muのMCMCサンプル格納用
mcmc_petal_width <- as.data.frame(matrix(nrow=N_mcmc, ncol=N))  # 予測分布MCMCサンプル格納用
# データごとにループ
for (i in 1:N){
  # 平均muのMCMCサンプル = 切片のMCMCサンプル + 係数のMCMCサンプル*Petal.Length
  mcmc_mu[,i] <- mcmc_Intercept + mcmc_b_petal_length*df_iris$petal_length[i] + mcmc_b_sepal_length*df_iris$sepal_length[i]
  # 事後予測分布のMCMCサンプルを正規分布乱数から生成
  mcmc_petal_width[,i] <- rnorm(n=N_mcmc, mean=mcmc_mu[,i], sd=mcmc_sigma)
}

# 予測区間の上下限を取得
threshold <- apply(mcmc_petal_width,
                   2,
                   quantile,
                   probs=c(lower, upper))
rownames(threshold) <- c("lower", "upper")
# プロット用のDataFrame
df_outlier <- data.frame(
  df_iris,
  t(threshold)
)
# 予測区間の外側のデータ（異常値）を判定
df_outlier <- data.frame(
  df_outlier,
  outlier = df_outlier$petal_width < df_outlier$lower | df_outlier$petal_width > df_outlier$upper
)

# 予測区間と外れ値データをプロット
# 説明変数2(sepal_length)ごとに予測区間をプロット
for(i_2 in 1:length(SEPAL_LENGTH_PRED)){
  sepal_length <- SEPAL_LENGTH_PRED[i_2] # 使用するsepal_length
  # 予測区間描画用ggplotオブジェクト
  p_pred <- ggplot() +
    theme_bw(base_size=18)
  
  # 試行回数が範囲内に入るデータを抜き出す
  if(i_2 == 1) sepal_length_min <- -2147483647 # 範囲の下限
  else sepal_length_min <- sepal_length - SEPAL_LENGTH_BY/2
  if(i_2 == length(SEPAL_LENGTH_PRED)) sepal_length_max <- 2147483647 # 範囲の上限
  else sepal_length_max <- sepal_length + SEPAL_LENGTH_BY/2
  data_sepal_filtered <- df_outlier[df_outlier$sepal_length>=sepal_length_min & df_outlier$sepal_length<sepal_length_max, ]
  
  # 95%予測区間と99%予測区間を取得
  qua_pred <- apply(mcmc_sample$petal_width_pred[,,i_2],
                  2,
                  quantile,
                  probs=c(0.005, 0.025, 0.50, 0.975, 0.995))
  df_qua_pred <- data.frame(
    petal_length=PETAL_LENGTH_PRED,
    t(qua_pred),
    check.names = FALSE
    )
  
  # 95%予測区間と99%予測区間をプロット
  p_pred <- p_pred +
    geom_ribbon(data=df_qua_pred, 
                aes(x=petal_length, ymin=`0.5%`, ymax=`99.5%`),
                fill='black', alpha=1/6) +
    geom_ribbon(data=df_qua_pred, 
                aes(x=petal_length, ymin=`2.5%`, ymax=`97.5%`),
                fill='black', alpha=2/6) +
    geom_line(data=df_qua_pred, 
              aes(x=petal_length, y=`50%`), 
              size=1) +
    geom_point(data=data_sepal_filtered, 
               aes(x=petal_length, y=petal_width, color=outlier), 
               size=2) +
    scale_colour_manual(values = c("blue", "red")) +
    labs(y='petal_width', title='Anomaly detection',
         subtitle=paste('sepal_length=', sepal_length, ' (', sepal_length_min, ' to ', sepal_length_max, ')', sep=""))
  plots_pred[[i_2]] <- p_pred
}
# 全ての図をプロット
plots_pred
```
